api-version: reviewpad.com/v3.x

metrics-on-merge: true

labels:
  small:
    color: "#294b69"
  medium:
    color: "#a8c3f7"
  large:
    color: "#8a2138"
  fast-track:
    color: "#76dbbe"


rules:


workflows:
  - name: fast-track
    description: Label PRs as a quick review
    if:
      - rule: $fileCount() == 1
    then:
      - $addLabel("fast-track")
          
  - name: add-label-with-size
    description: Label the size of PRs. Will help people when choosing PR for review
    always-run: true
    if:
      - rule: $size() <= 30
        extra-actions:
          - '$addLabel("small")'
      - rule: $size() > 30 && $size() <= 100
        extra-actions:
          - '$addLabel("medium")'
      - rule: $size() > 100
        extra-actions:
          - '$addLabel("large")'
          - $warning("Please consider splitting the pull request into smaller pull requests.")

  - name: check-for-linked-issued
    description: Print an info message to remind people to add a link to Jira, if there is one
    always-run: true
    if:
      - '!$hasLinkedIssues()'
    then:
      - '$info("For internal users: Please link this PR to a ticket.")'

  - name: too-big
    description: Print a warning to the user if there are more than 10 files in the PR
    if:
      - $fileCount() > 10
    then:
      - $warning("Please consider splitting the pull request into smaller pull requests.")

  - name: first-time-contributor
    description: Print a welcome message to the user if it's his first PR
    always-run: true
    if:
      - '$pullRequestCountBy($author(), "all") == 1'
    then:
      - '$commentOnce($sprintf("Welcome @%v! Thank you so much for your first pull request!", [$author()]))'

  - name: empty-description
    description: Fail the CI pipeline and print a warning message to the user if his description is empty
    always-run: true
    if:
      - $description() == ""
    then:
      - '$warn("The description is empty. Please add more information!")'
      - '$fail("Empty description")'
      
  - name: comment-on-pull-request
    description: Print nice message for submitting a pull request
    always-run: true
    if:
      - $description() != ""
    then:
      - $info("Thanks for this pull request!")
      - $info("Please make sure the CI is green before tagging reviewers!!!")
      
  - name: handle-conflicts
    description: Fail the CI pipeline and print a warning message in case of conflicts in the PR
    always-run: true
    if:
      - $hasGitConflicts()
    then:
      - $addLabel("conflicts")
      - $warn("This pull request has merge conflicts. Please resolve them and then rebase on the base branch.")  
      - '$fail("Conflicts found")'
    
  - name: protect-actions
    description: Disable merges for draft PR. MAke sure we don't merge a draft by mistake or manually or with a bugged automation
    if:
      - $isDraft()
    then:
      - $disableActions(["merge"])

  - name: disallow-binary-file
    description: Return an error when PR includes a binary file
    if:
      - $hasBinaryFile()
    then:
      - $close()
      - $fail("Please don't add any binary file into the repository")
      
  - name: auto-gen-file
    descrioption: Don't allow updating of auto-gen file
    always-run: true
    if:
      - $hasFileName("tyk-docs/content/shared/dashboard-config.md")
      - $hasFileName("tyk-docs/content/shared/gateway-config.md")
      - $hasFileName("tyk-docs/content/shared/mdcb-config.md")
      - $hasFileName("tyk-docs/content/shared/pump-config.md")
       - $hasFileName("tyk-docs/content/shared/x-tyk-gateway.md")
    then:
      - $fail("One of your files is auto gen file and as such cannot be update. Please remove it from the PR.")     
