api-version: reviewpad.com/v3.x

metrics-on-merge: true

labels:
  small:
    color: "#294b69"
  medium:
    color: "#a8c3f7"
  large:
    color: "#8a2138"

workflows:
  - name: add-label-with-size
    always-run: true
    if:
      - rule: $size() <= 30
        extra-actions:
          - '$addLabel("small")'
      - rule: $size() > 30 && $size() <= 100
        extra-actions:
          - '$addLabel("medium")'
      - rule: $size() > 100
        extra-actions:
          - '$addLabel("large")'

  - name: check-for-linked-issued
    always-run: true
    if:
      - '!$hasLinkedIssues()'
    then:
      - '$info("This pull request does not have a linked issue")'

  - name: too-big
    if:
      - $fileCount() > 10
    then:
      - $info("Please consider splitting the pull request into smaller pull requests.")

  - name: first-time-contributor
    always-run: true
    if:
      - '$pullRequestCountBy($author(), "all") == 1'
    then:
      - '$commentOnce($sprintf("Welcome @%v! Thank you so much for your first pull request!", [$author()]))'

  - name: empty-description
    always-run: true
    if:
      - $description()) == ""
    then:
      - '$warn("The description is empty. Please add more information!")'
      - '$fail("Empty description")'
      
  - name: comment-on-pull-request
    description: Example comment on pull request
    if:
      - $description() != ""
    then:
      - $info("Thanks for this pull request!")
      - $warn("Please make sure the CI is green before tagging reviewers.")
      - $info($sprintf("Welcome %s! Thank you!", [$description()]))

