api-version: reviewpad.com/v3.x

metrics-on-merge: true

labels:
  small:
    color: "#294b69"
  medium:
    color: "#a8c3f7"
  large:
    color: "#8a2138"
  fast-track:
    color: "#76dbbe"


rules:


workflows:
  - name: fast-track
    description: Label PRs as a quick review
    if:
      - rule: $fileCount() == 1
    then:
      - $addLabel("fast-track")
          
  - name: add-label-with-size
    description: Label the size of PRs. Will help people when choose PR for review
    always-run: true
    if:
      - rule: $size() <= 30
        extra-actions:
          - '$addLabel("small")'
      - rule: $size() > 30 && $size() <= 100
        extra-actions:
          - '$addLabel("medium")'
      - rule: $size() > 100
        extra-actions:
          - '$addLabel("large")'

  - name: check-for-linked-issued
    description: Message to remind people to add a link to Jira, if there is one
    always-run: true
    if:
      - '!$hasLinkedIssues()'
    then:
      - '$info("For internal users: Please link this PR to a ticket.")'

  - name: too-big
    description: Print a warning to the user if there are more than 10 files in the PR
    if:
      - $fileCount() > 10
    then:
      - $info("Please consider splitting the pull request into smaller pull requests.")

  - name: first-time-contributor
   description: Print welcome message to the user if it's his first PR
    always-run: true
    if:
      - '$pullRequestCountBy($author(), "all") == 1'
    then:
      - '$commentOnce($sprintf("Welcome @%v! Thank you so much for your first pull request!", [$author()]))'

  - name: empty-description
    description: Print warning message to the user if his description is empty
    always-run: true
    if:
      - $description() == ""
    then:
      - '$warn("The description is empty. Please add more information!")'
      - '$fail("Empty description")'
      
  - name: comment-on-pull-request
    description: Example comment on pull request
    if:
      - $description() != ""
    then:
      - $info("Thanks for this pull request!")
      - $warn("Please make sure the CI is green before tagging reviewers.")
      - $info($sprintf("Welcome %s! Thank you!", [$description()]))

